### ISSUE TITLE
Add documentation about how to use

### ISSUE THREAD

**Issue by scanepa** [Dome9/onboarding-scripts#1]
I think that there is a missing part about how to use external ID and account arn in the Dome9 web interface.

thanks for you great work

**Comment by alpalwal** [comment]
In the CloudFormation and Terraform sections, it's mentioned:
https://github.com/Dome9/onboarding-scripts/tree/master/AWS/cloudformation

Would you like to see it at the AWS/ level or is there more clarification needed in the specific sections as well? 

Thanks,
Alex

**Comment by scanepa** [comment]
Alex,
you're right, the readme in CF folder is clear, but if a user goes directly in the https://github.com/Dome9/onboarding-scripts/tree/master/AWS/cft_with_d9_api_automation and just grab the content of the https://github.com/Dome9/onboarding-scripts/tree/master/AWS/cloudformation directory and copy it into a S3 bucket without taking care of your README.md she/he can end up thinking she/he on-boarded her/his cloud but this not true.

So moving into the upper folder should be good.

My 2cents.
Stefano

**Comment by alpalwal** [comment]
Ah - for the API automation script, it actually generates a new external ID and applies it. 

allchar = string.ascii_letters + string.digits
extid = "".join(choice(allchar) for x in range(randint(12, 18)))

So in that case they should be good to go. I'll add in some more clarification though.

**Comment by scanepa** [comment]
You still need ID and KEY for API.

I read your code and I'm doing something similar using sceptre and
cloudformation.

**Comment by alpalwal** [comment]
It's in the readme:
- Ensure that both your Dome9 API keys and AWS API keys exist in this file as
well.

Should I be adding in more info here or exiting the script if they don't exist?

**Comment by scanepa** [comment]
Exiting the script should be a good solution.

All the best
Stefano

**Comment by alpalwal** [comment]
Please see the latest commit - it has been added. 

Thanks!
-Alex

    if d9id or d9secret or d9mode or awskey or awssecret == "":
        print ('Please ensure that all config settings in d9_aws_acct_add.conf are set.')
        sys.exit()
